### ISSUE TITLE
Can I used it with Arquillian 

### ISSUE THREAD

**Issue by hantsy** [atbashEE/jakarta-integration-testing#2]
Arquillian is the most popular testing framework for testing Jakarta EE components. 

Since Anquillian 1.7.0.Alpha10, it ships with a [AutoDeployment](https://github.com/hantsy/arquillian-autodeployment-example/blob/master/src/test/resources/META-INF/services/org.jboss.arquillian.container.test.spi.client.deployment.AutomaticDeployment) via service locator. The AutoDeloyment feature provides a `@BeforeDeployment` which can wait for the startup of containers.

I tried to use this feature with testcontainters in [my example project](https://github.com/hantsy/arquillian-autodeployment-example), the autodeployment did not build the test archive at all, finally it failed.

**Comment by rdebusscher** [comment]
No, that is not possible. And the idea is to deploy the production WAR for testing as recommended by the twelve-factor app principles. Not a specially crafted artifact containing test classes and test dependencies.

If AutoDeployment does not work, the Arquillian team should fix it (but the project is not really active anymore since version 1.7.0 is already for 4 years in alpha with no release in the meantime).
